name: Ubuntu Clang 15

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install tools
      run: |
        sudo apt update
        sudo apt --yes install clang-15 cmake libudev-dev

    - name: Build
      run: |
        mkdir out
        cd out
        cmake -DCMAKE_C_COMPILER=/usr/bin/clang-15 -DCMAKE_CXX_COMPILER=/usr/bin/clang++-15 ..
        make
