name: Ubuntu Clang

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install tools
      run: |
        sudo apt update
        sudo apt install clang cmake libudev-dev

    - name: Build
      run: |
        mkdir out
        cd out
        cmake -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ ..
        make
