name: Cppcheck

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Cppcheck
      run: |
        sudo apt update
        sudo apt --yes install cppcheck

    - name: Static analysis
      run: |
        cppcheck --project=ostrinkets.cppcheck --error-exitcode=1 --enable=warning,style
