name: Ubuntu G++

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install tools
      run: |
        sudo apt update
        sudo apt install cmake ninja-build g++ libudev-dev linux-headers-generic

    - name: Build
      run: |
        mkdir out
        cd out
        cmake -G Ninja -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ ..
        make
