name: Ubuntu g++12

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Install tools
      run: |
        sudo apt update
        sudo apt install g++-12 cmake libudev-dev

    - name: Build
      run: |
        mkdir out
        cd out
        cmake -DCMAKE_C_COMPILER=/usr/bin/gcc-12 -DCMAKE_CXX_COMPILER=/usr/bin/g++-12 ..
        make
